require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.0 # Replace with your Ruby version
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Performance:
  Enabled: true

RSpec:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Lint/MissingSuper:
  # Enabled: false
  AllowedParentClasses: [ApplicationService]
